version: '3.8'
services:
  wireshark:
    build: ./wireshark/
    container_name: wireshark-lua-api-declarations-wireshark
    # restart: always
    volumes:
      - ./test/dist:/test/dist
      - ./test/scripts:/test/scripts
      - ./test/captures:/test/captures
    tty: true
    working_dir: /test
    command: /test/scripts/test-all.sh
