version: '3.8'
services:
  tshark:
    build: ./tshark/
    container_name: wireshark-lua-api-declarations-tshark
    # restart: always
    volumes:
      - ./test/dist:/test/dist
      - ./test/scripts:/test/scripts
    tty: true
    working_dir: /test
    command: /test/scripts/test-all.sh
