name: Test
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  main:
    runs-on: ubuntu-22.04
    steps:
      - run: sudo apt-cache showpkg
      - run: sudo apt-get install -y tshark xvfb wireshark
        timeout-minutes: 5
      - uses: actions/checkout@v3
        timeout-minutes: 1
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
        timeout-minutes: 1
      - run: npm ci
        timeout-minutes: 1
      - run: npm test
        timeout-minutes: 10

